---
title: "Predicting Glucose Levels in Diabetes Patients"
author: "STATS 101A Group 35"
date: "2023-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readr")
library("tidyr")
library("dplyr")
library("car")
library("leaps")
library("vtable")
library("ggplot2")
library("gridExtra")
library("mice")
```

## Importing Dataset

```{r}
diabetes <- read.csv("diabetes.csv")
```

```{r}
head(diabetes)
```

```{r}
nrow(diabetes)
```

```{r}
count_zeros <- function(x) {
  sum(x == 0, na.rm = TRUE)
}

zero_counts <- sapply(diabetes[, 0:8], count_zeros)
(zero_counts_df <- data.frame(column_names = names(zero_counts), zero_count = zero_counts))
```

```{r}
ggplot(zero_counts_df, aes(x = column_names, y = zero_count)) +
  geom_bar(stat = "identity", fill = "cornflowerblue") +
  labs(title = "Number of 0s in Each Column",
       x = "Column Names",
       y = "Count of 0s") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
diabetes <- diabetes %>% 
  filter(Glucose != 0, BloodPressure != 0, Insulin != 0, BMI != 0, DiabetesPedigreeFunction != 0, Age != 0, Pregnancies != 0)

attach(diabetes)
```

```{r}
zero_counts <- sapply(diabetes[, 0:8], count_zeros)
(zero_counts_df <- data.frame(column_names = names(zero_counts), zero_count = zero_counts))
```

## Initial Model Analysis

#### Benchmark Model

```{r}
model <- lm(Glucose ~ Pregnancies + Insulin + BMI + BloodPressure + 
              SkinThickness + DiabetesPedigreeFunction + Age + Outcome)
summary(model)
```

```{r}
anova(model)
```

```{r}
model <- lm(Glucose ~ Insulin + BloodPressure + Age + Outcome)
summary(model)
```

```{r}
par(mfrow = c(2,2))
plot(model)
```

#### Multicolinearity Validation

```{r}
vif(model)
```

#### Scatterplot and Correlation Matrices

```{r}
df <- diabetes %>% select(Insulin, BloodPressure, Age, Outcome, Glucose)
```

```{r}
pairs(df, cex = 0.1)
cor(df)
```

#### EDA and Distribution

```{r}
plot.dist <- function(df) {
  plot.list <- lapply(names(df), function(column) {
    ggplot(df, aes_string(x = column)) +
      geom_density() +
      labs(title = column,
           x = column,
           y = "Density") +
      theme_minimal()
  })
  
  combined_plots <- do.call(grid.arrange, c(plot.list, ncol = 2))
  print(combined_plots)
}

plot.dist(df %>% select(Insulin, BloodPressure, Age, Glucose))
```

```{r}
st(diabetes)
```

#### Feature Transformations

```{r}
summary(powerTransform(cbind(Insulin, BloodPressure, Age) ~ 1))
```

```{r}
tInsulin <- log(Insulin)
tBloodPressure <- BloodPressure
tAge <- (Age^(-1)) / -1

invResPlot(lm(Glucose ~ tInsulin+tBloodPressure+tAge))
```

```{r}
tdf <- df

tdf["Insulin"] <- log(tdf["Insulin"])
tdf["Age"] <- (tdf["Age"]^(-1)) / -1

plot.dist(tdf %>% select(Insulin, BloodPressure, Age, Glucose))
```

## Transformed Model

```{r}
tGlucose <- log(Glucose)
tmodel <- lm(tGlucose ~ tInsulin + tBloodPressure + tAge + Outcome)

summary(tmodel)
```

```{r}
par(mfrow = c(2, 2))
plot(tmodel)
```

## Diagnostics and Evaluation

#### Leverages and Outliers

```{r}
hats <- hatvalues(tmodel)
leverages <- hats[hats > 2 * mean(hats)]
outliers <- hats[abs(rstandard(tmodel)) >= 2]

outliers[names(outliers) %in% names(leverages)]
```

```{r}
tdf[140, ]
```

#### Added Variable Plots

```{r}
par(mfrow=c(2, 2))
avPlot(tmodel, variable = "tBloodPressure", ask = F)
avPlot(tmodel, variable = "tInsulin", ask = F)
avPlot(tmodel, variable = "tAge", ask = F)
avPlot(tmodel, variable = "Outcome", ask = F)
```


## Variable Selection

#### All Possible Subsets Method

```{r}
summary(regsubsets(as.matrix(cbind(tInsulin, tBloodPressure, tAge, Outcome)), tGlucose))
```

```{r}
om1 <- lm(tGlucose ~ tInsulin)
om2 <- lm(tGlucose ~ tInsulin + Outcome)
om3 <- lm(tGlucose ~ tInsulin + tAge + Outcome)
om4 <- lm(tGlucose ~ tInsulin + tBloodPressure + tAge + Outcome)
possible_models <- list(om1, om2, om3, om4)
p <- 1:4
n <- nrow(diabetes)

criterias_breakdown <- matrix(0, nrow = 4, ncol = 5)
colnames(criterias_breakdown) <- c("Size", "Adj R2", "AIC", "AICc", "BIC")

# Adjusted R-squared
adj_R2 <- sapply(possible_models, function(mod) { summary(mod)$adj.r.squared })

# AIC
AIC <- sapply(possible_models, function(mod) { extractAIC(mod)[2] })

# AICc
AICc <- rep(0, 4)
for (i in p) {
  AICc[i] <- AIC[i] + ((2 * p[i]) * (p[i] + 2) * (p[i] + 3)) / (n - p[i] - 1)
}

# BIC
BIC <- sapply(possible_models, function(mod) { extractAIC(mod, k = log(n))[2] })

criterias_breakdown[, 1:5] <- c(p, adj_R2, AIC, AICc, BIC)
criterias_breakdown
```

```{r}
summary(om4)
```

## Final Model

```{r}
final_mod <- lm(tGlucose ~ tInsulin + tBloodPressure + tAge + Outcome)
summary(final_mod)
```

```{r}
detach("diabetes")
```




